### ISSUE TITLE
External table for loading data

### ISSUE THREAD

**Issue by bquinart** [philippechataignon/RNetezza#1]
Hi
I notice that performance for loading data into Netezza is not so good.
It looks like there is nothing build into the package to use the external table feature that Netezza offers.
Is this something that has been considered?
Do you have other mechanisms to improve write performance?
Tx
Bruno

**Comment by philippechataignon** [comment]
Hi,
I write this package for version 0.5.0 of dplyr which needs a DBI compliant interface. This package is used by [dplyrnz](https://github.com/philippechataignon/dplyrnz). In dplyrnz, I implement `copy_to` with external table, so the performance is correct.

**Comment by bquinart** [comment]
Thanks for the quick reply - answer is clear.
